### ISSUE TITLE
Issue with prettier 

### ISSUE THREAD

**Issue by timofei-iatsenko** [feelepxyz/dependabot-changesets#2]
Hello, we've recently encountered that the action started failing on our CI. I investigated the issue, and the root cause was that we added a shared prettier config to our monorepo. Here is outcome from my investigation: 

1. `@changesets/write` uses Prettier under the hood for `yml` files.
2. It should use workspace's version of prettier with workspace's config, because Prettier produce different result even in the minor versions bumps.
3. Since this action uses `ncc` to bundle everything together, it bundles a "default" version of Prettier which may not be compatible with workspace's version.
4. So `package` command should be updated to exclude prettier from the bundle: `ncc build --source-map --external prettier --license licenses.txt`  
5. Because action js file is located in completely different folder than workspace root, according to node module resolutions it has no chance to resolve packages from workspace. This could be fixed with a [`NODE_PATH`](https://nodejs.org/api/modules.html#loading-from-the-global-folders) variable pointing to the workspace's `node_modules`
   ```yml
     - run: node "${{ github.action_path }}/dist/index.js"
       shell: bash
       env:
         NODE_PATH: '${{ github.workspace }}/node_modules'
   ```
7. Therefore, the usage of this action is also changing, the user has to install packages before starting `dependabot-changesets` action. But because this action also has `actions/checkout` step it will reset all changes in the workspace including `node_modules` installed on previous steps. This step should be deleted from action to allow users to do preparation in the workspace before action run. 

Final `action.yml` after all changes should be: 

```yaml
# ...
runs:
  using: "composite"
  steps:
    - name: Dependabot metadata
      id: dependabot-metadata
      uses: dependabot/fetch-metadata@v2
      with:
        github-token: "${{ inputs.github-token }}"
    - run: node "${{ github.action_path }}/dist/index.js"
      shell: bash
      env:
        NODE_PATH: '${{ github.workspace }}/node_modules'
        DEPENDABOT_METADATA: '${{ steps.dependabot-metadata.outputs.updated-dependencies-json }}'
        DEFAULT_SEMVER_UPDATE_TYPE: '${{ inputs.default_semver_update_type }}'
    - run: |
        git config --local user.name "${{ inputs.commit_user_name }}"
        git config --local user.email "${{ inputs.commit_user_email }}"
        git add .changeset
        if ! git diff-index --quiet HEAD; then
          git commit --signoff -m "${{ inputs.commit_message }}"
          git push --set-upstream origin "HEAD:${{ inputs.branch }}"
        else
          echo "Found no changes to commit"
        fi
      shell: bash
```

And usage:

```yaml
name: "Dependabot Changesets"

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  changesets:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          # this is crucial, fetch entire history, otherwise "Failed to find where HEAD diverged from origin/main. Does origin/main exist?"
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Dependabot Changesets
        uses: feelepxyz/dependabot-changesets@main
```

## Notes: 

I checked the [source code](https://github.com/changesets/changesets/blob/main/packages/write/src/index.ts#L7-L14) of  `@changesets/write` and it seems Prettier should be optional, in case if the package is not found it should proceed without error, however it was not the case. So Prettier should be installed in the target workspace. 

The issue I described here requires significant changes in the structure and usage of the action, and this is might be not what you want. So I'm writing this here, rather as a share of knowledge then proposition of changes. In our case, we will go with our own fork.
